import { codepenEmbed } from "react-syntax-highlighter/dist/esm/styles/hljs";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SHOW_IMAGE_BACKDROP = "SHOW_IMAGE_BACKDROP";
export const CLOSE_IMAGE_BACKDROP = "CLOSE_IMAGE_BACKDROP";

export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const RETRIEVE_LOGGEDIN_USER = "RETRIEVE_LOGGEDIN_USER";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const RESTORE_TAXPRO = "RESTORE_TAXPRO";
export const DELETE_TAXPRO = "DELETE_TAXPRO";
export const RESTORE_USER = "RESTORE_USER";
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const ADD_USER_SUPERADMIN = "ADD_USER_SUPERADMIN";
export const UPDATE_USER_ACCOUNT_TYPE = "UPDATE_USER_ACCOUNT_TYPE";

// Taxpro Operations
export const TAXPRO_USERLISTSUCCESS = "TAXPRO_USERLISTSUCCESS";
export const TAXPRO_USERLIST_FAILURE = "TAXPRO_USERLIST_FAILURE";
export const TAXPRO_UPDATE = "TAXPRO_UPDATE";

export const TAXPRO_USERLIST_CREATESUCCESS = "TAXPRO_USERLIST_CREATESUCCESS";
export const TAXPRO_USERLIST_DETAILS = "TAXPRO_USERLIST_DETAILS";

//Account Operation
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const RESTORE_ACCOUNT = "RESTORE_ACCOUNT";
export const UPDATE_ACCOUNT_STATUS = "UPDATE_ACCOUNT_STATUS";
export const UPDATE_EMAIL_STATUS = "UPDATE_EMAIL_STATUS";

// export const CREATE_TAXPRO_USER_REQUEST = 'CREATE_TAXPRO_USER_REQUEST';
// export const CREATE_TAXPRO_USER_SUCCESS = 'CREATE_TAXPRO_USER_SUCCESS';
// export const CREATE_TAXPRO_USER_FAILURE = 'CREATE_TAXPRO_USER_FAILURE';

// export const FETCH_TAXPRO_USERS_REQUEST = 'FETCH_TAXPRO_USERS_REQUEST';
// export const FETCH_TAXPRO_USERS_SUCCESS = 'FETCH_TAXPRO_USERS_SUCCESS';
// export const FETCH_TAXPRO_USERS_FAILURE = 'FETCH_TAXPRO_USERS_FAILURE';

// export const FETCH_TAXPRO_USER_REQUEST = 'FETCH_TAXPRO_USER_REQUEST';
// export const FETCH_TAXPRO_USER_SUCCESS = 'FETCH_TAXPRO_USER_SUCCESS';
// export const FETCH_TAXPRO_USER_FAILURE = 'FETCH_TAXPRO_USER_FAILURE';

// export const UPDATE_TAXPRO_USER_REQUEST = 'UPDATE_TAXPRO_USER_REQUEST';
// export const UPDATE_TAXPRO_USER_SUCCESS = 'UPDATE_TAXPRO_USER_SUCCESS';
// export const UPDATE_TAXPRO_USER_FAILURE = 'UPDATE_TAXPRO_USER_FAILURE';

// export const DELETE_TAXPRO_USER_REQUEST = 'DELETE_TAXPRO_USER_REQUEST';
// export const DELETE_TAXPRO_USER_SUCCESS = 'DELETE_TAXPRO_USER_SUCCESS';
// export const DELETE_TAXPRO_USER_FAILURE = 'DELETE_TAXPRO_USER_FAILURE';

export const CREATE_TRANSCRIPTREQUEST = "CREATE_TRANSCRIPTREQUEST";
export const RETRIEVE_TRANSCRIPTREQUEST = "RETRIEVE_TRANSCRIPTREQUEST";
export const RETRIEVE_COMBINED_TRANSCRIPTREQUEST = "RETRIEVE_COMBINED_TRANSCRIPTREQUEST"